# @format
# 主题模式
theme:
  switch: true
  default: auto

# @format
# 网站信息
favicon:
  logo: false
  dark_logo: false
  icon16: /img/avatar.jpg
  icon32: /img/avatar.jpg
  appleTouchIcon: apple-touch-icon.png
  webmanifest: /site.webmanifest
  visibilitychange: false
  hidden: false
  showText:
  hideText:

# @format
# 作者信息
user:
  name: April
  first_name:
  last_name: April
  email: zyh_153697@163.com
  domain: https://april-one-st.github.io/
  avatar: /img/avatar.jpg
  describe: 网站简介
  ruleText: 一直往前看，未来会变得更加明亮的。

# @format
# 导航栏
top_bars:
  - title: Home
    url: /
  - title: Archives
    url: /archives
  - title: Links
    url: /links

# @format
# 侧边栏社交
sidebar:
  social: # 社交地址
    - name: github
      icon: fab fa-github
      url: https://github.com/April-one-st
  # @format
  # 打字动画
  typedTextPrefix: 《夏目友人帐》
  typedText: ["若结局非你所愿，那就在尘埃落定前奋力一搏"]
  # @format
  # 侧边栏个人信息
  info: # 个人信息
    - key: City
      val: ShangHai
    - key: Age
      val: 25

# @format
# 轮播图
banner:
  index:
    use_cover: true
    type: video
    bgurl: /img/banner.mp4
    bannerTitle: 愿神明偏爱，一切从欢
    bannerText: Hello!
  archive:
    type: video
    bgurl: /img/archives.mp4
    bannerTitle: Archive
    bannerText: 归档
# 页脚
footer:
  powered:
    enable: true
  beian:
    enable: false
    icp:
  copyrightYear: 2024
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 01/20/2024 00:00:00
  custom_text:

# 图片懒加载
lazyload:
  enable: true

# 版权信息
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: false
  clipboard: true

# 文章过期提示
notice_outdate:
  enable: true
  style: flat
  limit_day: 365
  position: top

# 图片丢失时默认加载图片
error_img:
  flink: /404.gif
  post_page: /404.jpg

# 图标切换
icons:
  # 主题切换图标
  sun: far fa-sun
  moon: far fa-moon
  # 首页视频播放
  play: fas fa-play
  # 邮箱
  email: far fa-envelope
  # 分类进入图标
  next: fas fa-arrow-right
  # 文章详情 日期
  calendar: far fa-calendar-alt
  # 文章详情 时间
  clock: far fa-clock
  # 文章详情 作者
  user: far fa-user
  # 返回顶部 v1.1.3+
  back_top: fas fa-arrow-up
  # 查询 v1.1.5+
  search: fas fa-search
  # 关闭 v1.1.5+
  close: fas fa-times
  # 打赏 v1.1.7+
  reward: fas fa-hand-holding-usd
  # 用户信息和文章目录切换 v1.2.10+
  user_tag: fas fa-user-alt
  toc_tag: fas fa-th-list
  # 右下角固定按钮 v1.2.11+
  read: fas fa-book-reader
  arrows: fas fa-arrows-alt-h
  # 代码高亮折叠 v2.0.0+
  double_arrows: fas fa-angle-double-down
  # 代码复制
  copy: fas fa-copy

  # 搜索功能
search:
  enable: true
  type: local

# 百度自动推送
baidu_push: true

# 代码高亮
highlight:
  title: mac
  height_limit: 200

# 文章目录
toc:
  enable: true
  list_number: true
  post_title: false
  max_depth: 3
  min_depth: 1

# 右下按钮
rightside:
  readmode: true
  aside: true

post_wordcount:
  wordcount: true # 单篇 字数统计
  min2read: true # 单篇 阅读时长

# 字数和阅读时间统计
wordcount:
  enable: true
  count: true
  time: true

swup: true

# 评论功能
comment:
  twikoo:
    enable: true
    envId: https://zhang-april-april.hf.space # 腾讯云环境id
    region: # 环境地域，默认为 ap-shanghai，如果您的环境地域不是上海，需传此参数
    option:
